name: breast-cancer-classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.3.0
      - torchvision==0.18.0
      - torchaudio==2.3.0
      - scikit-learn==1.5.1
      - opencv-python==4.10.0.84
      - scikit-image==0.24.0
      - Pillow==10.4.0
      - numpy==1.26.4
      - pandas==2.2.2
      - h5py==3.11.0
      - joblib==1.4.2
      - matplotlib==3.9.2
      - seaborn==0.13.2
      - plotly==5.24.1
      - tensorboard==2.16.2
      - mlflow==2.16.0
      - omegaconf==2.3.0
      - tqdm==4.66.5
      - pyyaml==6.0.2
      - pytest==8.3.3
